### ISSUE TITLE
Game crashes when mounting wheelchairs or wheeled stools

### ISSUE THREAD

**Issue by celestial-cookie** [Lyinginbedmon/Wheelchairs-2#6]
Happens in the backport, tested on 1.20.1. This doesn't happen in the V1.0 backport on the same instance. Wheeled Stools and Wheelchairs both cause the same crash, have not tested walkers yet. The world cannot be reloaded without immediately crashing the game again. 
[crash-2024-07-18_16.26.54-client.txt](https://github.com/user-attachments/files/16290103/crash-2024-07-18_16.26.54-client.txt)
[crash-2024-07-18_16.28.07-client.txt](https://github.com/user-attachments/files/16290104/crash-2024-07-18_16.28.07-client.txt)
[crash-2024-07-18_16.31.42-client.txt](https://github.com/user-attachments/files/16290105/crash-2024-07-18_16.31.42-client.txt)

**Comment by Lyinginbedmon** [comment]
From the crash report, it seems to be referencing a specific line in WheelchairsRideable where a call is made to a vanilla function made public by the mod's access widener. Since the report calls it private, the problem is most probably that the access widener isn't being applied in this version for some reason. I'll poke around and see if I can amend that.
https://github.com/Lyinginbedmon/Wheelchairs-2/blob/multi-loader-1.20.1/common/src/main/java/com/lying/entity/WheelchairsRideable.java#L300
