### ISSUE TITLE
[Suggestion] Wheelchair model adjustment + metal wheelchair 

### ISSUE THREAD

**Issue by Greenjoe12345** [Lyinginbedmon/Wheelchairs-2#9]
I am wondering if it would be possible to adjust the Wheelchair model so that it has four wheels rather then balancing on two. 
I am also wondering if a metal version could be made, which would be more suitable for modern based stuff, possible with a dyeable frame.
Guess a metal frame idea could also apply to other mobility aids too.

**Comment by Lyinginbedmon** [comment]
A 2-wheel aesthetic was chosen because Minecraft struggles with fine detail like the much smaller wheels at the front of real-world wheelchairs. It also presented a coding headache that is still present in walkers.

_However_, all entity models in the mod are composed from block models, meaning that a resource pack can change them in every detail as necessary. You could, therefore, use a resource pack to make (for example) the birch wheelchair look like a 4-wheeled metal wheelchair.

Dyeable frames are difficult to implement because the cushions are already dyeable, it's very tricky to make two separate dyeable components in one item without confusing the player.

**Comment by Greenjoe12345** [comment]
> A 2-wheel aesthetic was chosen because Minecraft struggles with fine detail like the much smaller wheels at the front of real-world wheelchairs. It also presented a coding headache that is still present in walkers.
> 
> _However_, all entity models in the mod are composed from block models, meaning that a resource pack can change them in every detail as necessary. You could, therefore, use a resource pack to make (for example) the birch wheelchair look like a 4-wheeled metal wheelchair.
> 
> Dyeable frames are difficult to implement because the cushions are already dyeable, it's very tricky to make two separate dyeable components in one item without confusing the player.

Ah that seems simple enough, would blockbench work for that? Main thing I was thinking about was if the smaller wheels would turn if it was done via resource pack

**Comment by Lyinginbedmon** [comment]
Yes, Blockbench will suffice for making any model you might desire for the wheelchairs, but the smaller wheels won't turn as that requires quite a heady bit of calculating and management to get working even for the walkers. However, at the likely scale of those wheels, it should hardly be noticeable.

**Comment by Greenjoe12345** [comment]
I'm afraid I don't know too much about modifying entities via resourcepacks, I hear another mod is needed to make resourcepacks able to show modified entity models? Would this be true for the wheelchairs too?

**Comment by Lyinginbedmon** [comment]
Absolutely not, the wheelchair models were _specifically_ made with "fake" block models and item models so that they can be altered without the need of a third-party mod. The only part of them that can't be changed with a resource pack is the positioning and rotation of the wheels (though the wheels themselves _can_ be changed as they are simply item models).

**Comment by Greenjoe12345** [comment]
![image](https://github.com/user-attachments/assets/a42d477a-edae-4593-ab3b-b22cfbb1af2d)
Yup, adding some legs was easy, I just need to figure out how to get the wheels in now

**Comment by Greenjoe12345** [comment]
![image](https://github.com/user-attachments/assets/dfb70c6a-6df2-4183-9395-e4ce16bd46dc)
I now have it working for the most part, except for the fact I cannot get it to render the texture of the wheels no matter what, if I try to put the path to where the wheel texture is, it'll just turn the entire wheelchair into a missing texture cube

**Comment by Lyinginbedmon** [comment]
That should just be a matter of tweaking the texture path, I expect there's a fair few tutorials on making resource packs that cover it. It can be a bit of a learning curve though, no doubt.

**Comment by Greenjoe12345** [comment]
![image](https://github.com/user-attachments/assets/55bbf583-547e-4d1e-97b5-12ab83daddb1)
got the path stuff working out

**Comment by Lyinginbedmon** [comment]
Ah congratulations!

**Comment by Greenjoe12345** [comment]
Would it be okay to upload the resource pack to modrinth? I have two versions planned
One that just adds the wheels to the wooden wheelchairs, and one that retextures the mobility aids to be in various colors.

**Comment by Lyinginbedmon** [comment]
By all means! I very much welcome community support for this project.

**Comment by Greenjoe12345** [comment]
How are the wheelchair textures in the mod's entity textures used? It appears they are pulling from the game's textures and not using those?

**Comment by Lyinginbedmon** [comment]
They're remnants of the original development of the wheelchair model, before it became a block model.
